// Generated by scripts/muqun-shots.ts. Do not edit by hand.
export const MUQUN_SHOTS = {
  'pad-session-dark': { width: 1180, height: 813 },
  'pad-session-light': { width: 1180, height: 813 },
  'screen-actions-dark': { width: 660, height: 1435 },
  'screen-actions-light': { width: 660, height: 1435 },
  'screen-files-dark': { width: 660, height: 1435 },
  'screen-files-light': { width: 660, height: 1435 },
  'screen-home-dark': { width: 660, height: 1435 },
  'screen-home-light': { width: 660, height: 1435 },
  'screen-panels-dark': { width: 660, height: 1435 },
  'screen-panels-light': { width: 660, height: 1435 },
  'screen-session-dark': { width: 660, height: 1435 },
  'screen-session-light': { width: 660, height: 1435 },
  'screen-terminal-dark': { width: 660, height: 1435 },
  'screen-terminal-light': { width: 660, height: 1435 },
  'theme-catppuccin-dark': { width: 660, height: 1435 },
  'theme-catppuccin-light': { width: 660, height: 1435 },
  'theme-gruvbox-dark': { width: 660, height: 1435 },
  'theme-gruvbox-light': { width: 660, height: 1435 },
  'theme-osuki-dark': { width: 660, height: 1435 },
  'theme-osuki-light': { width: 660, height: 1435 },
  'theme-rose-pine-dark': { width: 660, height: 1435 },
  'theme-rose-pine-light': { width: 660, height: 1435 },
  'theme-tokyo-night-dark': { width: 660, height: 1435 },
  'theme-tokyo-night-light': { width: 660, height: 1435 },
} as const;

export type MuqunShotName = keyof typeof MUQUN_SHOTS;

/**
 * A placement, without its mode suffix. The page asks for one of these and
 * gets both modes; only a name with a complete light/dark pair is offered.
 */
export type MuqunShotBase = MuqunShotName extends `${infer B}-${'light' | 'dark'}`
  ? B
  : never;
